name: >-
  ec2cronjob-prod_env_883efa96-1e5b-49f6-bddc-0b80d9e4fa93_app_4e51e67f-5296-4082-aa5f-308e2c97bff9
  Pipeline (Skyu Generated)
'on':
  push:
    tags:
      - v*
    paths: []
  workflow_dispatch: {}
  repository_dispatch:
    types: pipeline_80c0ad53-4b2a-45fc-b8fa-17419881835d
env:
  ENCODED_PIPELINE_SECRET: >-
    ${{secrets.GWENIWIICK_ENV_883EFA961E5B49F6BDDC0B80D9E4FA93_APP_4E51E67F52964082AA5F308E2C97BFF9_EC2CRONJOBPROD_ENV_883EFA961E5B49F6BDDC0B80D9E4FA93_APP_4E51E67F52964082AA5F308E2C97BFF9_YAML}}
  EC2_INSTANCE_TYPE: t2.2xlarge
  EC2_IMAGE_ID: ami-0c7217cdde317cfec
  EC2_SUBNET_ID: subnet-04efceeaff929dee8
  EC2_SECURITY_GROUP_ID: sg-05cb1a85417973c86
  EC2_SPOT_INSTANCE_BID_PRICE: '0.160800'
  DOCKER_COMPOSE_FILE_PATH: gwen/docker-compose.yml
  ADDITIONAL_COMPOSE_COMMANDS: 'docker-compose -f gwen/docker-compose.yml run gwen && '
  IMAGE_TAG: ${{github.event.client_payload.commitId || github.sha}}
  S3_SOURCE_PATH: ./gwen/output/reports
  S3_SYNC_URL: >-
    s3://skyu-client-reports/org_9f875a32-727f-4fb0-aeb6-ad3b32168642/project_88e61e3d-8f14-4fe8-b600-517e8138c28d/app_4e51e67f-5296-4082-aa5f-308e2c97bff9/gwen_outputs/${{github.event.client_payload.commitId
    || github.sha}}
  DEPLOY_STEP_SHOULD_DEPLOY: 'false'
jobs:
  code-scan:
    name: Code Scan
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions: write-all
    strategy:
      fail-fast: false
    steps:
      - name: 'Run :: Checkout repository for CodeQL'
        uses: actions/checkout@v4
      - name: 'Run :: Decoding Secrets 82565e45-ffe7-4efc-a203-bd5d5a05886d'
        run: |2-

                  if [ ! -x "$(command -v jq)" ]; then
                    echo "jq not found, installing..."
                    sudo apt-get update
                    sudo apt-get install -y jq
                  fi
                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Initialize CodeQL'
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: 'Run :: Autobuild for CodeQL'
        uses: github/codeql-action/autobuild@v3
      - name: 'Run :: Perform CodeQL Analysis'
        id: codeql-analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:${{matrix.language}}
      - name: 'Run :: Print & Upload CodeQL Report'
        run: |2-

                  SARIF_FILE=$(find "${{ steps.codeql-analysis.outputs.sarif-output }}" -name '*.sarif' -type f)
                  if [ -n "$SARIF_FILE" ]; then
                      echo "CodeQL Results"
                      cat "$SARIF_FILE" > ${{ env.IMAGE_TAG }}-codeql-result.sarif

                      echo "Uploading CodeQL Results to S3 :: ${{ env.IMAGE_TAG }}-codeql-result.sarif"
                      # Uploading Minified Trivy Resuls
                          response=$(curl -X POST ${{ env.S3_UPLOAD_ENDPOINT }} -H "Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}" -H "x-auth-by: sa" -H "x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}" -H "x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}" -H "x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}" -H "x-resource-id: ${{ env.DEPLOYMENT_APPLICATION_ID }}" -H "Content-Type: multipart/form-data" -F "file=@${{ env.IMAGE_TAG }}-codeql-result.sarif" -F "provider=aws" -F "resourceType=codeql-report" -F "cloudStoragePath=/${{ env.DEPLOYMENT_APPLICATION_ID }}/codeql_results/")
                          if echo "$response" | grep -q '"success":true'; then
                            echo "SUCCESS :: $response"
                          else
                            echo "FAILED :: $response"
                          fi
                  else
                      echo "SARIF file not found."
                  fi
  start-runner:
    name: Start Runner
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      EC2_HOST: ${{ env.EC2_HOST }}
      EC2_INSTANCE_ID: ${{ env.EC2_INSTANCE_ID }}
    steps:
      - name: 'Run :: Decoding Secrets 90a594e5-022f-4b6f-8944-ede2d5a5b7e5'
        run: |2-

                  if [ ! -x "$(command -v jq)" ]; then
                    echo "jq not found, installing..."
                    sudo apt-get update
                    sudo apt-get install -y jq
                  fi
                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Configure AWS credentials d60d0983-e593-4fe8-9af7-d435e3feb730'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Create AWS Spot Instance'
        run: |2-

                # Get GitHub Actions runner registration token
                response=$(curl -s -X POST         -H 'Accept: application/vnd.github+json'         -H 'Authorization: Bearer ${{ env.pat }}'         -H 'X-GitHub-Api-Version: 2022-11-28'         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners/registration-token)

                RUNNER_REG_TOKEN=$(echo "$response" | jq -r .token)
                
                if [ $RUNNER_REG_TOKEN != "null" ]; then
                  USER_DATA="#!/bin/bash
                  
                  apt update && apt install -y apt-transport-https
                  apt-get update && apt install docker.io -y
                  echo \"Docker Installed\"

                  usermod -aG docker ubuntu
                  newgrp docker
                  echo \"ubuntu Added to Groups\"

                  # docker-compose
                  curl -L 'https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64' -o /usr/local/bin/docker-compose
                  echo \"Docker Compose Installed\"
                  chmod +x /usr/local/bin/docker-compose
                  echo \"Docker Compose Permissions added\"
                  
                  # Install GitHub Actions runner
                  mkdir /home/ubuntu/actions-runner && cd /home/ubuntu/actions-runner
                  curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
                  echo \"Github Runner Installed\"

                  # Extract the installer
                  tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz
                  echo \"Github Runner Installer Extracted\"
                  
                  # Run GitHub Actions runner configuration
                  export RUNNER_ALLOW_RUNASROOT=1
                  yes '' | ./config.sh --url https://github.com/${GITHUB_REPOSITORY} --token $RUNNER_REG_TOKEN --labels EC2_SKYU_RUNNER_${{env.IMAGE_TAG}}
                  echo \"Github Runner Configured\"
                  
                  # Run GitHub Actions runner
                  yes '' | ./run.sh 
                  echo \"Github Runner UP!\"
                  "
                  
                  ENCODED_USER_DATA=$(echo -n "$USER_DATA" | sed 's/^[[:space:]]*//' | base64 -w 0)
                  echo "ENCODED_USER_DATA :: $ENCODED_USER_DATA"
                  echo "LAUNCH SPECIFICATION JSON :: {\"ImageId\":\"${{ env.EC2_IMAGE_ID }}\",\"InstanceType\":\"${{ env.EC2_INSTANCE_TYPE }}\",\"SecurityGroupIds\":[\"${{ env.EC2_SECURITY_GROUP_ID }}\"],\"SubnetId\":\"${{ env.EC2_SUBNET_ID }}\",\"UserData\":\"$ENCODED_USER_DATA\"}"
                  
                  REQUEST_ID=$(aws ec2 request-spot-instances         --spot-price "${{ env.EC2_SPOT_INSTANCE_BID_PRICE }}"         --instance-count 1         --type "one-time"         --launch-specification "{\"ImageId\":\"${{ env.EC2_IMAGE_ID }}\",\"InstanceType\":\"${{ env.EC2_INSTANCE_TYPE }}\",\"SecurityGroupIds\":[\"${{ env.EC2_SECURITY_GROUP_ID }}\"],\"SubnetId\":\"${{ env.EC2_SUBNET_ID }}\",\"UserData\":\"$ENCODED_USER_DATA\"}"         --query 'SpotInstanceRequests[0].SpotInstanceRequestId'         --output text)
                  aws ec2 wait spot-instance-request-fulfilled --spot-instance-request-ids $REQUEST_ID
                  INSTANCE_ID=$(aws ec2 describe-spot-instance-requests --spot-instance-request-ids $REQUEST_ID --query 'SpotInstanceRequests[*].InstanceId' --output text)
                  HOSTNAME=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
                  
                  echo "EC2_HOST=$HOSTNAME" >> $GITHUB_ENV
                  echo "EC2_INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV 
                else
                    echo "$response"
                  exit 1
                fi
              
  compose-job:
    name: Compose Job
    permissions: write-all
    runs-on: self-hosted
    needs:
      - start-runner
    steps:
      - name: Start
        run: |2-

              echo " Starting GitHub Action!" && 
              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
              
      - name: 'Run :: Checkout repository'
        uses: actions/checkout@v2
      - name: 'Run :: Checkout Specific Commit'
        if: ${{ github.event.client_payload.commitId != null }}
        run: git checkout ${{ github.event.client_payload.commitId }}
      - name: 'Run :: Decoding Secrets 9a3ff7d9-e1af-466f-a2ad-74f139c9906d'
        run: |2-

                  if [ ! -x "$(command -v jq)" ]; then
                    echo "jq not found, installing..."
                    sudo apt-get update
                    sudo apt-get install -y jq
                  fi
                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Configure AWS credentials d8476498-b842-4646-abe3-6958805591eb'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Docker Compose'
        run: |2-

              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} build && docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} up -d &&
              ${{env.ADDITIONAL_COMPOSE_COMMANDS}}
              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} down -v
              
      - name: 'Run :: Sync Outputs to S3 bucket'
        run: |2-

              if [ ! -x "$(command -v aws)" ]; then
                echo "AWS CLI not found, installing..."
                sudo apt update
                sudo apt install -y awscli
              fi

              if aws s3api head-bucket --bucket skyu-client-reports 2>/dev/null; then
                echo "Bucket skyu-client-reports exists."
              # Create the S3 bucket if it doesn't exist
              else
                echo "Creating bucket skyu-client-reports..."
                aws s3api create-bucket --bucket skyu-client-reports --region ${{ env.region }}
              fi

              aws s3 sync ${{ env.S3_SOURCE_PATH }} ${{ env.S3_SYNC_URL }}
              
  deploy:
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - compose-job
    steps:
      - name: 'Run :: Decoding Secrets f5f221fa-e4fb-402e-bdc8-0769d1988948'
        run: |2-

                  if [ ! -x "$(command -v jq)" ]; then
                    echo "jq not found, installing..."
                    sudo apt-get update
                    sudo apt-get install -y jq
                  fi
                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Deploy and Notify Resource Service'
        run: |2-

              response=$(curl -d "appType=Ec2CronJob&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.IMAGE_TAG }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ github.run_id }}&commitDetails[commitHash]=${{ github.sha }}&commitDetails[commitAvatar]=https://github.com/${{ github.event.head_commit.author.name }}.png&commitDetails[commitTime]=${{ github.event.head_commit.timestamp }}&commitDetails[commitMessage]=\"${{ github.event.head_commit.message }}\"&commitDetails[commitUser]=${{ github.event.head_commit.author.name }}" -X PATCH -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}' -H 'x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.DEPLOYMENT_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded' '${{ env.DEPLOYMENT_ENDPOINT }}')

              if echo "$response" | grep -q '"success":true'; then
                echo "SUCCESS :: $response"
              else
                echo "FAILED :: $response"
              fi
            
  stop-runner:
    name: Stop Runner
    permissions: write-all
    runs-on: ubuntu-latest
    needs:
      - start-runner
      - compose-job
    if: ${{ always() }}
    steps:
      - name: 'Run :: Decoding Secrets a80627e8-775f-406c-b1fa-e874449dcb0e'
        run: |2-

                  if [ ! -x "$(command -v jq)" ]; then
                    echo "jq not found, installing..."
                    sudo apt-get update
                    sudo apt-get install -y jq
                  fi
                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                
      - name: 'Run :: Configure AWS credentials 0c3de25a-4fb6-466f-813a-c3df19654974'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.roleARN }}
          role-session-name: skyu-pipeline-assume-role-session
          aws-region: ${{ env.region }}
      - name: 'Run :: Stop AWS Spot Instance'
        run: |2-

                aws ec2 terminate-instances --instance-ids ${{ needs.start-runner.outputs.EC2_INSTANCE_ID }}
                gh_runner_label=${{ needs.start-runner.outputs.EC2_SKYU_RUNNER }}

                response=$(curl -X GET         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners         -H 'Authorization: Bearer ${{ env.pat }}'
                )
                offline_skyu_runners=$(echo "$response" | jq '.runners | map(select((.labels? | any(.name == "EC2_SKYU_RUNNER_${{env.IMAGE_TAG}}"))))')
                echo "Offline Skyu Runners :: $offline_skyu_runners"
                
                echo "Attempting to remove offline skyu runners..."
                for runner in $(echo "$offline_skyu_runners" | jq -r '.[].id'); do
                  echo "Triggering action for runner ID: $runner"
                  curl -X DELETE         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners/$runner           -H 'Authorization: Bearer ${{ env.pat }}'
                done
              
